server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_generica?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Root112030
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

tienda.admin-inicial.cedula=0
tienda.admin-inicial.usuario=admininicial
tienda.admin-inicial.contrasena=admin123456
